### ISSUE TITLE
oecd docsting improvment

### ISSUE THREAD

**Issue by konstantinstadler** [konstantinstadler/pymrio#113]
for the latest release, only strings are possible for specfiying years (OECD provides the mrios in bundles). 
We need to better explain that in the docstrings.

**Comment by hazimhussein** [comment]
I have linked a pull request to this issue, in the pull request, I have updated the documentation for OECD downloader as well as the docstring, I have also added a code so as if single years are passed, the corresponding bundle is downloaded
