### ISSUE TITLE
"import pymrio" is missing in parser.py

### ISSUE THREAD

**Issue by cfrancois7** [konstantinstadler/pymrio#12]
Just a small missing:

[At line 190](https://github.com/konstantinstadler/pymrio/blob/master/pymrio/tools/parser.py#L190) `EXIOError` is called through `pymrio.core`. It's an error: `import pymrio` is missing and `EXIOError` is actually available through `pymrio.core.mriosystem`

I propose to import with `from pymrio.core.mriosystem import EXIOError` and at line 190 just call `raise EXIOError('EXIOBASE files missing')`

**Comment by konstantinstadler** [comment]
Errors are coded differently now.
Fixed in version 0.2.2.2
