### ISSUE TITLE
TypeError: sum() got an unexpected keyword argument 'sort'

### ISSUE THREAD

**Issue by danielhorengreenford** [konstantinstadler/pymrio#13]
Running on python 3.5.1
numpy==1.10.4

Did not allow 'sort' keyword, had to manually remove 'sort=false' from all lines present in core/mriosystem.py

Worked after those instances were removed!

Thanks for the code :+1:

**Comment by konstantinstadler** [comment]
Dont know exactly why sort was in there - worked for pandas version before 0.16 - after updating pandas I can now reproduce the bug.
Fixed in version 0.2.2.2
