### ISSUE TITLE
Version number hard coded in parser.py needs to be changed for new EXIOPOL versions

### ISSUE THREAD

**Issue by danielhorengreenford** [konstantinstadler/pymrio#14]
parser.py returns "missing files" error for new EXIOPOL version (2.2.2) since it's hard coded for version 2.2.0. Just needs to be changed in file names in parser.py. Maybe change version input parameter to have a three-part name holder (i.e. 2.x.y)?

**Comment by konstantinstadler** [comment]
Fixed in version 0.3.0
