### ISSUE TITLE
Divide by zero error in iomath.py

### ISSUE THREAD

**Issue by danielhorengreenford** [konstantinstadler/pymrio#15]
Issue on line 109 in iomath.py

I changed: 
recix[recix==np.inf]=0

to:
if x == 0:
        recix = 0
    else:
        recix = 1/x

since it was returning a trying to divide by zero error that stopped computation when parsing in EXIOPOL pxp 2.2.2

**Comment by konstantinstadler** [comment]
Fixed in version 0.2.2.2
