### ISSUE TITLE
Instructions for install with conda?

### ISSUE THREAD

**Issue by majeau-bettez** [konstantinstadler/pymrio#20]
It seems conda does not come with a recent enough version of pandas to install pymrio. Might be worth updating the instructions?

When I try:
`guillaume@ciraigLinux:~$ conda create --name io -c konstantinstadler pymrio`

I get:

> Fetching package metadata ...........
> Solving package specifications: 
> 
> PackageNotFoundError: Packages missing in current channels:
>             
>   - pymrio -> pandas >=0.22.0
>   - pymrio -> requests >=2.18
> 
> We have searched for the packages in the following channels:
>             
>   - https://conda.anaconda.org/konstantinstadler/linux-64
>   - https://conda.anaconda.org/konstantinstadler/noarch
>   - https://repo.continuum.io/pkgs/free/linux-64
>   - https://repo.continuum.io/pkgs/free/noarch
>   - https://repo.continuum.io/pkgs/r/linux-64
>   - https://repo.continuum.io/pkgs/r/noarch
>   - https://repo.continuum.io/pkgs/pro/linux-64
>   - https://repo.continuum.io/pkgs/pro/noarch
>             
> 
>

**Comment by konstantinstadler** [comment]
Strange, when I just do
`conda install -c konstantinstadler pymrio`
everything works fine.
Not so familiar with the `conda create --name` stuff, perhaps you first have to create it, than update the packages and than install pymrio into this environment? Or perhaps do a `conda update --all` first? Still on paternity leave - so just a quick guess...

**Comment by konstantinstadler** [comment]
Works with pymrio version 0.4.0 without problems
