### ISSUE TITLE
Exio3 parser permission error

### ISSUE THREAD

**Issue by MaximeAgez** [konstantinstadler/pymrio#35]
Hi, 
I am trying to use the parser of exiobase3 and I get a permission error. It seems that the parser only accepts zip files? Yet, when I use the zip file directly downloaded from exiobase website it tells me KeyError: "There is no item named 'mrIot3.0.txt' in the archive", and when i use the unzipped file i get the following error:

io = pymrio.parse_exiobase3('C://Users/Maxime/Desktop/Thesis/Bdd/IOT_2011_pxp/')
---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
<ipython-input-5-8d7abbe77594> in <module>()
----> 1 io = pymrio.parse_exiobase3('C://Users/Maxime/Desktop/Thesis/Bdd/IOT_2011_pxp/')

C://Users/Maxime/Desktop/Thesis/Modules_Python/pymrio-master\pymrio\tools\ioparser.py in parse_exiobase3(zip_file, path_in_zip, version, iosystem, year, charact)
    498     # read the data into a dicts as pandas.DataFrame
    499     logging.info('Read exiobase3 from {}'.format(zip_file))
--> 500     zip_file = zipfile.ZipFile(zip_file)
    501 
    502     core_data = {exio_table: pd.read_table(

C:\Users\Maxime\Anaconda3\lib\zipfile.py in __init__(self, file, mode, compression, allowZip64)
   1088             while True:
   1089                 try:
-> 1090                     self.fp = io.open(file, filemode)
   1091                 except OSError:
   1092                     if filemode in modeDict:

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Maxime\\Desktop\\Thesis\\Bdd\\IOT_2011_pxp'

**Comment by konstantinstadler** [comment]
Hi, I can not reproduce the bug. Are you using the latest publicly available exiobase version: you should have a exio34.ini file in the extracted directory.

**Comment by konstantinstadler** [comment]
Hi,

can you do
`
import pymrio
import sys
print("Python :{}, pandas: {}, pymrio: {}".format(sys.version_info, pymrio.pd.__version__, pymrio.__version__))

`
and send me the output.

**Comment by konstantinstadler** [comment]
There is your problem: you are far behind the current release. Current pymrio version: 0.3.8 -   you use 0.2.2. Run

pip install pymrio --upgrade

This should solve your problem. Anyway, please let me know if it worked.

**Comment by konstantinstadler** [comment]
No problem. Happy to help!
