### ISSUE TITLE
Can't find the characterization matrix in parse_exiobase2.

### ISSUE THREAD

**Issue by MaximeAgez** [konstantinstadler/pymrio#36]
Hi Konstantin,
I'm using parse_exiobase2 and am providing the path to the CREEA characterization xlsx file provided by Exiobase2 and it works fine. 
My issue though, I cannot find any characterization dataframe inside the pymrio object. I can only find the associated impacts to each commodity (pymrio.impact.S). Am I missing this characterization matrix dataframe? or is it not possible to isolate it through pymrio?

Thank you!
Maxime Agez

**Comment by konstantinstadler** [comment]
Hi, pymrio only includes the characterized impacts, but does not store the characterization matrix itself (this should be in included in the download of exiobase2). Do you think there would be any benefit in having it also available in pymrio? Closing that issue for now, fell free to reopen if this is still open
