### ISSUE TITLE
Parse from zipfile on MS Windows

### ISSUE THREAD

**Issue by konstantinstadler** [konstantinstadler/pymrio#40]
Parsing directly from the zip file does not work (at least for EXIOBASE 3) because the path separator is different in Windows and in the zip file.

**Comment by rafaellaurenti** [comment]
I'm using a Mac and I'm getting an error too. I've tried both the zipped and unzipped file. Any ideas of a solution? Many thanks in advance. 

![image](https://user-images.githubusercontent.com/39736183/66161344-60e3c480-e62c-11e9-8f6c-2cdea86a279c.png)

**Comment by konstantinstadler** [comment]
This should be solved in version 0.4.1
