### ISSUE TITLE
Missing values in the MR Emissions file

### ISSUE THREAD

**Issue by GeorgeNash** [konstantinstadler/pymrio#44]
Hi Konstantin,

There are some seemingly missing values from Exiobase V2, I was hoping you could clear up this confusion for me.

I am interested in the emissions intensity.

```
pop_vec = pd.read_csv("/Users/nash/dev/emitwise-flask/cleaning/data/exiobase/populations.txt", sep="\t", index_col=0)
exio2 = pymrio.parse_exiobase2(path='/Users/nash/dev/data/exio_ixi', charact=True, popvector=pop_vec)
df = exio2.emissions.S
```

When looking at `exio2.emissions.S` there are some surprising omissions. For example, under "Cattle Farming", the non combustible methane emissions are zero?

Best,
George

**Comment by konstantinstadler** [comment]
Hi, this is an EXIOBASE issue, not a issue of pymrio. EXIOBASE V2 is also out of date and will not receive any updates. I recommend to switch to EXIOBASE 3:
https://environmentalfootprints.org/blog/exiobase3
