### ISSUE TITLE
AttributeError: 'Extension' object has no attribute 'D_fp'

### ISSUE THREAD

**Issue by BenPortner** [konstantinstadler/pymrio#47]
Hi Konstantin,

just downloaded pymrio and cannot wait to use it! Thanks for providing a package for MRIO manipulation! 
Here is one thing I realized: When going through the test example in the readme, I get an error:

```python
AttributeError: 'Extension' object has no attribute 'D_fp'
```

The error occurs when calling `test_mrio.emissions.D_fp`. I downloaded the latest version directly from github via 

```git
pip install git+https://github.com/konstantinstadler/pymrio
```

Here is my system info: Python 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)] on win32

Maybe the attribute was renamed meanwhile?

**Comment by konstantinstadler** [comment]
Hi Ben,
Thanks for the info. This is some remnant of a previous naming. D_fp was renamed to D_cba - I fixed it in the readme.
See also  https://pymrio.readthedocs.io/en/latest/terminology.html
