### ISSUE TITLE
Pypi sdist does not include all package data

### ISSUE THREAD

**Issue by Didou09** [konstantinstadler/pymrio#50]
Motivation:
--------------
* Following my comment in PR #49 , I think that the setup.py and/or the MANIFEST.in are incomplete since the installation using pip does not include the necessary directory `pymrio/mrio_models/exio20` and all its content.
* This is probably the same problem behind the comment by @bixiou in issue #9 

Idea:
-------
* Try to include it in setup.py and MANIFEST.in
* May also have something to do with the fact that pymrio/mrio_models/exio20 does not have a __init__.py, such that it may not be considered as part of the package in sdist

**Comment by konstantinstadler** [comment]
Tested on windows and it seems to work now
