### ISSUE TITLE
More info about regions ?

### ISSUE THREAD

**Issue by Didou09** [konstantinstadler/pymrio#57]
As a beginner user, I somehow feel it would be nice to have a method, other than get_regions() that would return more info about the regions: full name, member of an organisation...

I can propose a first version, and you'll decide whether you want to include it or not

**Comment by konstantinstadler** [comment]
Hi,
In essence, the regions are just strings. Any method you would use would be tied to a specific MRIO - I tried to be as generic as possible in pymrio. For the countries, I developed coco (https://github.com/konstantinstadler/country_converter ) which should just do that. I was thinking to extend coco with more country information (e.g. GDP, population, ...) but then decided to not do that:
This would either require some database backend which needs to be maintained (e.g. for new population data, GDP, ... which might be conflicting between data sources) OR some API access to the data sources to retrieve the information. There are already tools out there doing that, so I decided to not reinvent the tool there   - basically, I did not come across a use case which wasn't handled by any other tool yet. Anyway, if you encounter a missing functionality, feel free to implement.

**Comment by Didou09** [comment]
OK thanks for the answer,
Just the possibility of return the full names together with the ultra-short 2-letter strings would be nice, I don't recognize of all them.
From a first look it seems that country_converter can do that, so I'll just go for this already-existing solution and come back to you if a use-case requires more.
Thanks

**Comment by konstantinstadler** [comment]
Yeah, I know it is confusing sometimes. But these are the letters used by the MRIO compiliers. For EXIOBASE we tried to follow ISO2 + some custom ones. Other MRIOS (e.g. Eora) use 3 letters which often follows ISO 3 but not always - thats why there are separate categories in coco.

**Comment by Didou09** [comment]
I get from the following output that Exiobase 3 considers 250 countries, of which many are grouped into a single general area (like WF for example which groups  Zambia, Zimbabwe, Western Sahara...)

Does that mean that there is no country not taken into account in Exiobase 3 ? Are all existing countries either considered individually or in a group, or are there missing countries not taken into account at all ?


![image](https://user-images.githubusercontent.com/5929562/101362657-b060f880-38a0-11eb-9b76-72fb4cb2f0d1.png)

**Comment by Didou09** [comment]
Congrats, by the way, this library looks like a nice piece of code :+1:

**Comment by konstantinstadler** [comment]
Thanks. Yes, the point of the global MRIOs is to cover the global economy. Of course, it is tricky to say if actually cover everything as there are conflicting statistics. We use the global GDP from the UN as the total and scale the remaining countries to it - is the global GDP of the UN correct? Who knows... Same for countries - how many are there? Who knows... (even in the countries we model explicitly  -  we get comments by Chinese Profs that Taiwan is not a country and we should label it  a "Region of China" ...)

**Comment by konstantinstadler** [comment]
feel free to reopen if necessary and thanks for your continuous help and suggestions 👍🏽
