### ISSUE TITLE
Citing pymrio as part of academic work

### ISSUE THREAD

**Issue by tamarm** [konstantinstadler/pymrio#58]
Hi Konstantin,
First, thank you so much for this package, it has been super helpful as part of the EEIO analysis for my thesis: 'Food Waste reduction via sharing economy - environmental analysis and rebound effect.

I am starting to write down the thesis and would like to cite this package. 
(e.g. on geopandas citing - http://citebay.com/how-to-cite/geopandas/)
How should I cite this package?
Thank you so much, Tamar

**Comment by konstantinstadler** [comment]
Hi,
Great to hear that you find it useful. Very much appreciate citations!
For the citations it depends a little on your timeline.
There is currently a paper under review (2nd round) at Journal of Open Research Software https://github.com/konstantinstadler/pymrio_article
If you need to cite it immediately you can either:

- cite the preprint of the article (it is on Zenodo, see he badge)
- cite the doi of pymrio (each release is on Zenodo as well)
- there is also a poster from some years ago (https://zenodo.org/record/997892#.X_x7YMco_Sc)

Think it depends a little if you want to cite the software you used (then I would cite the doi of the software directly) or give a description of the software (then the preprint or the poster).

So many choices, but I hope that helped a little
best
kst

**Comment by tamarm** [comment]
Thank you for all these options :)
For my drafts I will cite the pymrio doi directly, and will check if the paper was published before submission
