### ISSUE TITLE
accessing emissions computation from exiobase3

### ISSUE THREAD

**Issue by robingirard** [konstantinstadler/pymrio#64]
I'm trying to access the GHG emission decomposition for different countries in Europe with consumption/production/net trade along different years. I followed the documentation here https://pymrio.readthedocs.io/en/latest/notebooks/working_with_exiobase.html#Exploring-EXIOBASE starting with year 2015. 
year= 2015
exio3 = pymrio.parse_exiobase3(path='IOT_'+str(year)+'_pxp.zip')
exio3.meta
exio3.get_regions()
exio3.calc_all()

I have a satellite extension but no impact. 
Thanks in advance for your help
Robin

**Comment by konstantinstadler** [comment]
Yeah, the docs are a little outdated - I will fix that. 
did you use the latest exiobase version (https://zenodo.org/record/4588235)?  you can download them automatically with pymrio: https://pymrio.readthedocs.io/en/latest/notebooks/autodownload.html#EXIOBASE-3-download
