### ISSUE TITLE
exio3.impact.get_rows() yields AttributeError: 'IOSystem' object has no attribute 'impact'

### ISSUE THREAD

**Issue by JNS728** [konstantinstadler/pymrio#66]
I am trying to calculate consumption-based impacts with Exiobase v3.8.1 for which I followed instructions on [https://pymrio.readthedocs.io/en/latest/notebooks/working_with_exiobase.html](https://pymrio.readthedocs.io/en/latest/notebooks/working_with_exiobase.html).

```Python
import pymrio

exio3_path = 'data-exiobase/IOT_2021_pxp'
exio3 = pymrio.parse_exiobase3(path=exio3_path)

# Exploring EXIOBASE
exio3.meta
exio3.get_sectors()
exio3.get_regions()
list(exio3.get_extensions())

# Calculating the system and extension results
exio3.calc_all()

# The available impact data can be checked with:
list(exio3.impact.get_rows())
```

The last row returns the error `AttributeError: 'IOSystem' object has no attribute 'impact'`. Does anyone have a suggestion why?

**Comment by konstantinstadler** [comment]
whats the output of exi3.get_extensions()?

**Comment by JNS728** [comment]
```Python
list(exio3.get_extensions())
Out[2]: ['impacts', 'satellite']
```

**Comment by konstantinstadler** [comment]
then there is a typo in the docs. Try
list(exio3.impacts.get_rows())

**Comment by JNS728** [comment]
Yes, nice ... just a typo `impacts` instead of `impact` works. Thank you very much!
