### ISSUE TITLE
Surprising coefficients in matrix S for Exiobase 3

### ISSUE THREAD

**Issue by mbesserve** [konstantinstadler/pymrio#72]
Hi and thanks for this great tool!
I uploaded Exiobase 3 and computed the impacts using pymrio.
While interpreting the data, I noticed that the 4th impact variable
'GHG emissions (GWP100) | Problem oriented approach: baseline (CML, 2001) | GWP100 (IPCC, 2007)'
in matrix S has surprising discrepancies between sources of electricity production, and across countries
in 2012, this is for the US
![grafik](https://user-images.githubusercontent.com/25327106/122559212-573c0380-d03f-11eb-9fe9-68f23e4c21d7.png)

for France
![grafik](https://user-images.githubusercontent.com/25327106/122571323-e56ab680-d04c-11eb-8307-3fa74bef9b84.png)

for Germany
![grafik](https://user-images.githubusercontent.com/25327106/122560003-55267480-d040-11eb-9e91-8806ca8e705b.png)

I am suprised in particular by the high coefficient of solar photovoltaic in the US and Germany, and the anomaly of geothermal in Germany. Given those are clearly not given particularly low electricity prices...
I understand that it might not be related at all to pymrio, but instead a bug in Exiobase. Just wanted to double check with you if this looks legit from the pymrio side.
Thanks!

Here is the code I use:
```python
import pymrio
import matplotlib.pyplot as plt

year = 2012
mrioDat = pymrio.load('/data/exiobase/pkl/'+str(year)+'/')
mrioImp = pymrio.load('/data/exiobase/pkl/'+str(year)+'/impacts')
sectors = mrioDat.get_sectors()
country = 'FR'
S = mrioImp.S[country].to_numpy()
plt.figure()
plt.table([[sectors[k][:min(40,len(sectors[k]))],
                    np.round(S[3,k]/1000,2)] for k in range(127,140)],loc='center',colWidths=[.6,.4])

```

**Comment by konstantinstadler** [comment]
hi, this is not pymrio related but for EXIOBASE. I forwared it to the EXIBOASE email list, lets see if we can check that.

**Comment by mbesserve** [comment]
Many thanks! I would have started there if I new the mailing list of Exiobase. I saw a google group but it seems only used for announcements. Is it possible for external people to subscribe to this list (and if yes can you forward me the link)?
