### ISSUE TITLE
OECD ICIO 2021 Release

### ISSUE THREAD

**Issue by jaimeoliver1** [konstantinstadler/pymrio#86]
Hello, 

first of all, thanks very much for the pymrio package, it is really useful!

I've noticed the OECD released the new wave of ICIO tables in November 2021: https://www.oecd.org/sti/ind/inter-country-input-output-tables.htm

If that's ok I'll file a pull request in the following days with the ingestion of the new tables. Hope that helps!

**Comment by konstantinstadler** [comment]
Thanks a lot for the contribution!

**Comment by jaimeoliver1** [comment]
@konstantinstadler can you please trigger the pipeline to include this feature in the Pypi repository?

**Comment by konstantinstadler** [comment]
running the cross os tests now, hope I can do the release tomorrow

**Comment by konstantinstadler** [comment]
ok, its on pypi. Conda usually take a day to pick that up

**Comment by konstantinstadler** [comment]
btw: do you have a twitter handle to tag you in the release note?

**Comment by jaimeoliver1** [comment]
Thanks very much! 
I'm not an active twitter user (although I connected with you on LinkedIn)
