### ISSUE TITLE
Remove region from MRIO system?

### ISSUE THREAD

**Issue by graebnerc** [konstantinstadler/pymrio#94]
Is there a way to remove a region from the IO system? It could be useful if one compute accounts a sub-part of the regions covered by MRIO (e.g. footprints only within the EU28). Any help is appreciated, thank you very much!

**Comment by konstantinstadler** [comment]
A full removal would not make sense, b/c then you would loose the interconnections for the footprint analysis. But you can of course aggregate all other countries to one Rest of the World region (aggregation is covered in the docs).

However, I would also avoid doing that, as you loose a lot of detail for the calculation. 
It is better to always do the calcs on the highest level of detail and aggregate later.
Thus, sum the footprints of the EU countries after doing the footprint calculations

**Comment by graebnerc** [comment]
Thanks for the super quick reply and explanation:)
Great work with the package, its highly appreciated!!
