### ISSUE TITLE
Wrong final demands of utilities in exiobase 3.8.1 and 3.8.2

### ISSUE THREAD

**Issue by MaximeAgez** [konstantinstadler/pymrio#95]
Hi @konstantinstadler & @rich-wood,
I think there are pretty massive issues in the final demands of the versions 3.8.1 & 3.8.2 of exiobase.

In the screenshots below I'm sharing the final demand of electricity in China in 2019.

In version 3.8, we have a final demand that makes sense.
![image](https://user-images.githubusercontent.com/24285636/207906034-d1ff6767-a75c-4fe8-aa6a-682d8eb95b70.png)

From 3.8.1 though, issues arise:
![image](https://user-images.githubusercontent.com/24285636/207906278-1cb71a30-8bd2-4a34-9155-490d1aef37ec.png)
The total demand does not make sense anymore (that would be something like 0.1€ of **annual** electricity bill per Chinese resident) and the grid mix itself is not present since there is basically only electricity from petroleum. Something is clearly wrong with the data.

The problem is continued in 3.8.2 as well:
![image](https://user-images.githubusercontent.com/24285636/207906744-e7336227-3651-4b90-b483-7ecdfb9f2af7.png)

For electricity the demands for Netherlands and Ireland also seem to be wrong.

**Comment by MaximeAgez** [comment]
Similar issues with the demand in natural gas which completely disappears for some reason in China and other countries.

![image](https://user-images.githubusercontent.com/24285636/207907523-c49cebac-f073-4b6f-ac09-febb5937aa82.png)

**Comment by konstantinstadler** [comment]
Hi,

Many thanks for reporting that.
However, these are not pymrio issues but EXIOBASE. I forwarded them internally to Richard and we keep that in mind for the next version.

Best
Konstantin
